### ISSUE TITLE
C-Sibelia.py does not create VCF file

### ISSUE THREAD

**Issue by Rhinogradentia** [bioinf/Sibelia#176]
Hi,

I'm trying to call Variants using C-Sibelia.py. I've managed to do it with other sequences (very similar) before, but now I am stuck with a sequence combination where no VCF file is created (no maf and no unmapped file as well). What could be the reason for this? How can I fix this? I've already tried the loose option and changed the block size, but neither of this changed something. 

The call I am using looks like this:

`C-Sibelia.py -o outdir/ --maf seq1_vs_seq2.maf -v seq1_vs_seq2.vcf -u seq1_vs_seq2.txt seq1.fa seq2.fasta`

In contrary to other runs all the tmp-files are still there (*block.anchors, *block.fasta, blocks_coords*.txt)

Thank you for your help

Best Regards,

Nadine

**Comment by ilyaminkin** [comment]
Hi Nadine,

It looks like the alignment got interrupted. It could be due to a bug in the aligner we use (LAGAN), or some problems with Sibelia. Can you share .fasta files? Or at least blocks_coords.txt?

**Comment by Rhinogradentia** [comment]
Hey there,

I can provide the blocks_coords.txt. It's attached.

[blocks_coords3.txt](https://github.com/bioinf/Sibelia/files/1291599/blocks_coords3.txt)
[blocks_coords2.txt](https://github.com/bioinf/Sibelia/files/1291600/blocks_coords2.txt)
[blocks_coords1.txt](https://github.com/bioinf/Sibelia/files/1291601/blocks_coords1.txt)
[blocks_coords0.txt](https://github.com/bioinf/Sibelia/files/1291602/blocks_coords0.txt)

Thank you,

**Comment by ilyaminkin** [comment]
You may try to change the parameter -m slightly. If it is a problem with the aligner, maybe slightly changed output will get rid of "bad" data.

**Comment by Rhinogradentia** [comment]
Thank you, sorry for the late answer.
I've tried that now with several values.
Below -m 500 I get the same result. From -m 1500 on I get following Error:
`An error occured: [Errno 2] No such file or directory: 'Seq1_vs_Seq2.vcf'`. The resulting files are the blocks_coord txt files, blocks_sequences.fasta, coverage_report.txt, d3_blocks_diagram.html, genomes_permuations.txt and the circos folder.
I've also tried to create the file beforehand with touch. This changed nothing in the outcome. 

Do you have any further idea?

Best Regards,

**Comment by Rhinogradentia** [comment]
Manage to produce a valid vcf file now with -m 800 and a shorter out-dir-path. Maybe the result file would have been to big with -m 1500...

Anyway - thanks for your help.

Best Regards
