### ISSUE TITLE
Issue when building from source: lagan

### ISSUE THREAD

**Issue by nickp60** [bioinf/Sibelia#178]
Hi,
I am attempting to add Siberia to Bioconda.  Building on Linux seems to be going just fine, but I keep having issues with building on OSX.  I have tried to build both version 3.0.5 and 3.0.6.  The errors are below, and links to the full build logs:

for 3.0.5, the error starts at line 2201:
```
-- Build files have been written to: /anaconda/conda-bld/sibelia_1511652846387/work/Sibelia-3.0.5/build
+ make
Scanning dependencies of target lagan
[  3%] Creating directories for 'lagan'
[  6%] Performing download step (DIR copy) for 'lagan'
[  9%] No patch step for 'lagan'
[ 12%] No update step for 'lagan'
[ 15%] No configure step for 'lagan'
[ 18%] Performing build step for 'lagan'
Undefined symbols for architecture x86_64:
  "_findPrev", referenced from:
      _connectToPrev in fchaos-6f75cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [../chaos] Error 1
make[3]: *** [all] Error 2
make[2]: *** [lagan/src/lagan-stamp/lagan-build] Error 2
make[1]: *** [CMakeFiles/lagan.dir/all] Error 2
make: *** [all] Error 2
```

for 3.0.6, the error looks like this snippet, starting at line 2813:
```
[  3%] Creating directories for 'lagan'
[  6%] Performing download step (DIR copy) for 'lagan'
[  9%] No patch step for 'lagan'
[ 12%] No update step for 'lagan'
[ 15%] No configure step for 'lagan'
[ 18%] Performing build step for 'lagan'
rightinfluence.cpp:21:2: error: reference to 'end' is ambiguous
        end.score = -2;
        ^
rightinfluence.cpp:3:18: note: candidate found by name lookup is 'end'
Fragment origin, end;
                 ^
```
3.0.5
https://travis-ci.org/bioconda/bioconda-recipes/jobs/307296455
3.0.6
https://travis-ci.org/bioconda/bioconda-recipes/jobs/307303787

I am a total novice in terms of debugging things at compiling.  Any tips for getting around these errors?

Thanks in advance!

**Comment by mbargull** [comment]
The offending line is:
https://github.com/bioinf/Sibelia/blob/09e53d4eba6f398cbfd3ba990769b635d2f9cdac/src/lagan/src/glocal/structs.h#L15

That `using namespace std;` is propagated to all files that include `structs.h` and creates the ambiguity since it introduces `std::end` into the current namespace.

**Comment by ilyaminkin** [comment]
Hi Marcel, I will take a look after Monday.

**Comment by ilyaminkin** [comment]
I pushed to master, could you pull and try to build?

**Comment by ilyaminkin** [comment]
I don't have a Mac to test, so please forgive if it does not work.

**Comment by mbargull** [comment]
Me neither 😄 -- but Travis CI's OSX instance built it just fine: https://travis-ci.org/bioconda/bioconda-recipes/builds/309563419?utm_source=github_status&utm_medium=notification.
Are planning on tagging a new release with this change? I could use that then in https://github.com/bioconda/bioconda-recipes/pull/6970 to make it available from Bioconda for both OSes.

**Comment by mbargull** [comment]
Hi there, any chance the current master can be tagged with `v3.0.7` (`v3.0.8`?)?
Otherwise this issue is resolved.

**Comment by mbargull** [comment]
Thanks for the tag @ilyaminkin!
