### ISSUE TITLE
Repeated markers and repeated contigs information are outputted

### ISSUE THREAD

**Issue by TsorngWeiWu** [bioinf/Sibelia#184]
Here maybe some output problem

(1)
I have used the following multi-fasta file as my algorithm input (For uploading demand, I transformed .fna format into .txt format.)

[contigMerged.txt](https://github.com/bioinf/Sibelia/files/2453700/contigMerged.txt)

 and at the beginning I need to know all participating contigs name of this file so I use the folowing command

      sibelia -s loose -m 900000 [the path of above .fna file]  [current working dictionary]

![image](https://user-images.githubusercontent.com/10471840/46579682-f1eb8400-ca48-11e8-9b17-8b0ceb3ef0c3.png)

Of course you can know that it is almost impossible to find such large synteny block size for at least 900000, so the output file in blocks_coords.txt will just list all name of contigs like following

![image](https://user-images.githubusercontent.com/10471840/46058583-4ad83400-c18e-11e8-8065-9f5aeaf4c1e1.png)

But when I use it, I found name of contigs repeatedly outptted like following (the far left number is row number in vim)

![image](https://user-images.githubusercontent.com/10471840/46058746-d782f200-c18e-11e8-99e8-11cb9228459a.png)
![image](https://user-images.githubusercontent.com/10471840/46058758-e1a4f080-c18e-11e8-8fff-7fd967c40187.png)

(2)
The same in blocks_coords.txt file with normal sibelia parameter, I found that marker repeatedly outputted. I choos the following as target and reference respectively.

target:
[contigMerged.txt](https://github.com/bioinf/Sibelia/files/2418249/contigMerged.txt)
 
reference:
[GCA_000157795.txt](https://github.com/bioinf/Sibelia/files/2453707/GCA_000157795.txt)

then use this command for marker information (SyntenySize is 50 for this example)

                            sibelia -k [paraset] -m 50 [GCA_000157795.fna] [contigMerged]
![image](https://user-images.githubusercontent.com/10471840/46059791-537f3900-c193-11e8-8ce5-05dd89dbdec2.png)

paraset is congiured like following

1
20 100

finally check content in genomes_permutation and the first few lines also output repeated name of contigs

![image](https://user-images.githubusercontent.com/10471840/46060025-31d28180-c194-11e8-88b3-6b6e91b440fe.png)
![image](https://user-images.githubusercontent.com/10471840/46060045-3e56da00-c194-11e8-8d16-b688efa2cc67.png)

and marker number 28 on the same contigs repeatedly appear

![image](https://user-images.githubusercontent.com/10471840/46060427-ea4cf500-c195-11e8-8d63-23a14bde9451.png)

the same problem also happens in genomes_permutations.txt

![image](https://user-images.githubusercontent.com/10471840/46060625-95f64500-c196-11e8-9cf6-1942ee98a77d.png)
![image](https://user-images.githubusercontent.com/10471840/46060642-9f7fad00-c196-11e8-9c10-830932c9b211.png)

(3) Here I can offer my dataset for this problem 

[dataset.zip](https://github.com/bioinf/Sibelia/files/2418410/dataset.zip)

Each species has its own directory and each has three reference .fna file under any species as reference.
File "contigMered.v3.randOrd" is target  (or query) 

You can try the same parameter I used in (1)(2)

**Comment by ilyaminkin** [comment]
Hi,

In the file that you uploaded (GCA_000157795.txt), there are no FASTA records that contain ids of the form "gi|....|..." . The are all of the form DS<some number>.1, like DS999838.1. Are you sure you uploaded the right file?

**Comment by TsorngWeiWu** [comment]
Sorry for that error uploading files.   I have corrected  it and take a look at it please.

**Comment by TsorngWeiWu** [comment]
> Hi,
> 
> In the file that you uploaded (GCA_000157795.txt), there are no FASTA records that contain ids of the form "gi|....|..." . They are all of the form DS.1, like DS999838.1. Are you sure you uploaded the right file?
