### ISSUE TITLE
Single contig self alignment - repeats

### ISSUE THREAD

**Issue by fungal-spore** [bioinf/Sibelia#191]
Hi,
I'd like to have a self-alignment for a single contig to visualize repetitive elements.
I tried using duplicate fasta files, which works somewhat but there is lots of 'noise'.
Is there a way to have Sibelia align to itself using a single fasta seq?
Hope that makes sense!
Thanks :)

**Comment by fungal-spore** [comment]
I figured out a way to do what I want, for future users.
I made a second fasta file with only one nucleotide in it.

e.g.
>place-holder
A

Then I could run
Sibelia -s fine contig-with-repeats.nt place-holder.nt -m 50 -o ./sibelia_output

This provided nice output of single contig with many of its repetitve sections shown.

**Comment by iminkin** [comment]
Hi @fungal-spore,

I am glad you figured it out. Just in case, you don't even need a placeholder, you can just run:

Sibelia -s fine contig-with-repeats.nt -m 50 -o ./sibelia_output

**Comment by fungal-spore** [comment]
I can't believe I didn't try that lol thanks!
