### ISSUE TITLE
make install requires sudo

### ISSUE THREAD

**Issue by vyahhi** [bioinf/Sibelia#45]
$ make install
[ 20%] Built target divsufsort
Scanning dependencies of target Sibelia
[ 25%] Building CXX object CMakeFiles/Sibelia.dir/main.cpp.o
[ 30%] Building CXX object CMakeFiles/Sibelia.dir/outputgenerator.cpp.o
[ 35%] Building CXX object CMakeFiles/Sibelia.dir/blockfinder.cpp.o
[ 40%] Building CXX object CMakeFiles/Sibelia.dir/bulgeremoval.cpp.o
[ 45%] Building CXX object CMakeFiles/Sibelia.dir/edge.cpp.o
[ 50%] Building CXX object CMakeFiles/Sibelia.dir/graphalgorithm.cpp.o
[ 55%] Building CXX object CMakeFiles/Sibelia.dir/serialization.cpp.o
[ 60%] Building CXX object CMakeFiles/Sibelia.dir/synteny.cpp.o
[ 65%] Building CXX object CMakeFiles/Sibelia.dir/platform.cpp.o
[ 70%] Building CXX object CMakeFiles/Sibelia.dir/vertexenumeration.cpp.o
Linking CXX executable Sibelia
[100%] Built target Sibelia
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/Sibelia
CMake Error at cmake_install.cmake:43 (FILE):
  file cannot create directory: /usr/share/sibelia.  Maybe need
  administrative privileges.

make: **\* [install] Error 1

**Comment by divya1srv** [comment]
While installing Sibelia in Linux getting below error:

**$ cmake ../src/
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!**

Kindly suggest the solution,
I will highly thankful for the help.
